library(shiny)
library(mrgsolve)
library(dplyr)
library(ggplot2)
library(scales)

# This software is intended for research and exploratory analysis only. 
# It should not be used for clinical decision-making, diagnosis, treatment, 
# or patient management before any prospective clinical validations. 
# The results generated by this tool are for informational purposes only. 
# The developers assume no responsibility or liability for any outcomes resulting from the use of this R Shiny code.


## Infliximab code

Infliximab_model_code <- 
  
  "
$Global

$PROB
Minimal PBPK to predict the fetal exposure of infliximab during pregnancy assuming 70 Kg weight

$PARAM @annotated
// {Physiological Parameters}
GAinitial         : 0               : GA is gestational age (weeks). GAinitial is time the simnulation to be started at in respect to pregnancy, defaulted at 0 (beginnig of the pregnancy)
TVVlymph          : 5.2             : Volume of lymph (L) 
TVL               : 2.9             : Total lymph flow (L/day) 
TVKp              : 0.8             : Fraction of interstitial space available for antibody distribution
TVRfT             : 0.945           : Vascular reflection coefficient for tight tissues
TVRfL             : 0.697           : Vascular reflection coefficient for leaky tissues
TVRflymph         : 0.2             : Lymphatic vascular reflection coefficient
TVCLm             : 0.1184          : Additional maternal clearance term for infliximab (L/day)
TVkef             : 0.021           : Fetal clearance term for infliximab (day-1)
  
// {Endosome 1 (Vascular) Parameters}
TVCLup            : 1.48            : Endothelial nonspecific pinocytosis rate (L∙day−1) 
TVCLe             : 5.75472         : Lysosome catabolism clearance (L∙day−1)
TVkrec            : 127.7193        : Endosome recycling rate constant (day−1)
TVVe1             : 0.00342         : Endosome volume for nonspecific pinocytosis (L) 
TVkon             : 18.0576         : Antibody FcRn association rate constant (nM-1.day-1) in endosomes
TVkoff            : 13132.8         : Antibody-FcRn complex (FcRnA) dissociation rate constant (day−1) in endosomes


// {PK Parameters}
//ka              :            : absorption rate constant (day-1)
//BA              :            : SC Bioavailability


$CMT @annotated //All are amounts, except for FcRn and FcRnA are concentrations:
// {Plasma Compartment}
depot             : depot compartment for SC administration
A_plasma          : Antibody in plasma
m_auc             : Maternal AUC
  
// {Tight Tissue Compartment}
A_Tight           : Antibody in tight tissue

// {Leaky Tissue Compartment}
A_Leaky           : Antibody in leaky tissue

// {Lymph Compartment}
A_lymph           : Antibody in lymph
  
// {Endosome 1 Compartment} 
A_e1              : Antibody in endosome 1
FcRn_e1           : FcRn endosome 1
FcRnA_e1          : FcRn-Antibody endosome 1

// {Placenta Blood} 
A_placenta_blood  : Antibody in the vascular compartment of the placenta

// {Endosome 2 Compartment - synchiotrophoblast} 
A_e2              : Antibody in endosome 2
FcRn_e2           : FcRn in endosome 2
FcRnA_e2          : FcRn-Antibody in endosome 2

// {Endosome 3 Compartment - fetal endothelial cells} 
A_e3              : Antibody in endosome 3
FcRn_e3           : FcRn in endosome 3
FcRnA_e3          : FcRn-Antibody in endosome 3

// {Fetal Blood Compartment} 
A_plasma_fetal    : Antibody in Fetal Blood
f_auc             : Fetal AUC

$OMEGA
0.09 // Variance for FcRn expression variability in endosomes 2 and 3
0.09
0.09
0
0
0
0
0.09
0.09
0.09
0.09
0.09
0.09
0.09
0.09
0.09
0.09
0.09
0.09
0.09
0.09




$MAIN 
double tad = self.tad();

// Define non-zero ODE initial conditions
FcRn_e1_0=49800; //Concentration of FcRn in endasome 1 (nM)

double GA = GAinitial + TIME/7; //GA is gestational age (weeks). GAinitial is time the simnulation to be started at in respect to pregnancy, defaulted at 0 (beginnig of the pregnancy)

//double FcRn expression equation as a variable to be included in the differential equations
if (GA < 0) double M2 = 0;
if (GA >= 0) M2 = 0.0007*exp(0.2236*GA)*exp(ETA(1))*10000*2.3;
if (GA < 0) double M3 = 0;
if (GA >= 0) M3 = 0.0007*exp(0.2236*GA)*exp(ETA(1))*10000*0.9;



// Add variabilities for fixed values
double Vlymph = TVVlymph * exp(ETA(2));
double L   =  TVL  * exp(ETA(3));   
double Kp  =  TVKp    * exp(ETA(4));   
double RfT = TVRfT  * exp(ETA(5));   
double RfL =  TVRfL   * exp(ETA(6)); 
double Rflymph =  TVRflymph   * exp(ETA(7));   
double CLm =  TVCLm      * exp(ETA(8));     
double kef = TVkef      * exp(ETA(9));   
double CLup = TVCLup    * exp(ETA(10));   
double CLe =  TVCLe    * exp(ETA(11));     
double krec =  TVkrec  * exp(ETA(12));   
double Ve1  = TVVe1  * exp(ETA(13));      
double kon  =  TVkon  * exp(ETA(14));         
double koff = TVkoff   * exp(ETA(15));     

double VisfT = Visf*0.65; //Volume of interstitial fluid/Intracellular Water in the tight tissue (L)
double VisfL = Visf*0.35; //Volume of interstitial fluid/Intracellular Water in the tight tissue (L)
double LT = L*0.33; //Lymph flow in the tight tissues (L/day)
double LL = L*0.67; //Lymph flow in the leaky tissues (L/day)

//double Vplasma: Volume of plasma (L)
if (GA < 0) double Vplasma = 2.5* exp(ETA(16));  
if (GA >= 0) Vplasma = ( 2.50 - 0.0223*GA + 0.0042*pow(GA, 2) - 0.00007*pow(GA, 3)  )*exp(ETA(16));

//double Visf: Volume of interstitial fluid/Intracellular Water (L)
if (GA < 0) double Visf = 19.81* exp(ETA(17));  
if (GA >= 0) Visf = ( 19.81 + 0.5941*GA - 0.0007*pow(GA, 2) )* exp(ETA(17));  

//double Vplacenta: Volume of placenta (L)
if (GA < 2) double Vplacenta = 0;
if (GA >= 2 & GA < 9) Vplacenta = ( (-1.7646* GA + 0.91775* pow(GA, 2) - 0.011543* pow(GA, 3))/1000 ) * exp(ETA(18)); 
if (GA >= 9) Vplacenta = ( (0.0 - 0.716* GA + 0.9149* pow(GA, 2) - 0.0122* pow(GA, 3))/1000 )* exp(ETA(18));

//double Qplacenta: Blood flow to the placenta (L/day)
if (GA <= 3.6) double Qplacenta = 0;
if (GA > 3.6)  Qplacenta = ( 0.059176 * Vplacenta * 1000 *24 )* exp(ETA(19));

//double Vplacenta_blood: Volume of placenta blood (L)
if (GA < 0) double Vplacenta_blood = 0.00001;
if (GA >= 0) Vplacenta_blood = ( 0.5*0.4*((1.9593*exp(0.1417*GA))/1000) )* exp(ETA(20)); 

//double Vplasma_fetal: Volume of the fetus blood (L)
if (GA < 0) double Vplasma_fetal = 0.00001;
if (GA >= 0) Vplasma_fetal = ( 0.5*0.6*((1.9593*exp(0.1417*GA))/1000) )* exp(ETA(21));


// {Endosome 2 (Maternal) Parameters}
//double CLupp: Endothelial nonspecific pinocytosis rate (L∙day−1) in placenta
if (GA <= 0) double CLupp = 0.001;
if (GA > 0) CLupp = ((5E-06*pow(GA, 2)) - (5E-06*GA) - 7E-05)*CLup;


//double CLep: Lysosome catabolism clearance (L∙day−1) in placental endosome
if (GA <= 0) double CLep = 0.001;
if (GA > 0) CLep = ((5E-06*pow(GA, 2)) - (5E-06*GA) - 7E-05)*CLe;


//double Ve2: Endosome volume for nonspecific pinocytosis (L) for placental endosome
double Ve2 = 0.1*1.8*((5E-06*pow(GA, 2)) - (5E-06*GA) - 7E-05)*Ve1;


// {Endosome 3 (Fetal) Parameters}
//double Ve3 Endosome volume for nonspecific pinocytosis (L) for fetal endosome
double Ve3 = 1.8*(1.428571E-05)*(-(0.0628939*pow(GA, 4)) + (6.623713*pow(GA, 3)) - (251.9597*pow(GA, 2)) + (4222.827*GA) - 26256.56)*Ve1;



$ODE 
// { Absorption compartment }
//dxdt_depot = -depot*ka;

// { Plasma }

// Antibody
dxdt_A_plasma = +L*A_lymph/Vlymph
                +krec*Ve1*FcRnA_e1
                -Qplacenta*A_plasma/Vplasma
                +Qplacenta*A_placenta_blood/Vplacenta_blood
                -(1-RfT)*LT*A_plasma/Vplasma
                -(1-RfL)*LL*A_plasma/Vplasma
                -CLup*A_plasma/Vplasma -CLm*A_plasma/Vplasma;
                

// { Tight tissue }

// Antibody in tight tissue
dxdt_A_Tight = (1-RfT)*LT*A_plasma/Vplasma
              -(1-Rflymph)*LT*A_Tight/(VisfT*Kp);


// { Leaky tissue }

// Antibody in leaky tissue
dxdt_A_Leaky = (1-RfL)*LL*A_plasma/Vplasma
              -(1-Rflymph)*LL*A_Leaky/(VisfL*Kp);

// { Placenta blood}
dxdt_A_placenta_blood = Qplacenta*A_plasma/Vplasma
                        -CLupp*A_placenta_blood/Vplacenta_blood
                        -Qplacenta*A_placenta_blood/Vplacenta_blood;
                        

// { Lymph }

// free antibody in lymph
dxdt_A_lymph = (1-Rflymph)*LT*A_Tight/(VisfT*Kp)
              +(1-Rflymph)*LL*A_Leaky/(VisfL*Kp)
              -L*A_lymph/Vlymph;

// { Endosome compartment 1 }

// Antibody in endosome 1
dxdt_A_e1 = -kon*A_e1*FcRn_e1
            +koff*FcRnA_e1*Ve1
            -CLe*A_e1/Ve1
            +CLup*A_plasma/Vplasma;

// FcRn in endosome 1
dxdt_FcRn_e1 = -kon*FcRn_e1*A_e1/Ve1
              +koff*FcRnA_e1
              +krec*FcRnA_e1;

// FcRn-Antibody in endosome 1
dxdt_FcRnA_e1 = kon*FcRn_e1*A_e1/Ve1
                -koff*FcRnA_e1
                -krec*FcRnA_e1;

// { Endosome compartment 2 }

// Antibody in endosome 2
dxdt_A_e2 = -kon*A_e2*FcRn_e2
            +koff*FcRnA_e2*Ve2
            -CLep*A_e2/Ve2
            +CLupp*A_placenta_blood/Vplacenta_blood;

// FcRn in endosome 2
dxdt_FcRn_e2 = -kon*A_e2*FcRn_e2/Ve2
              +koff*FcRnA_e2
              +krec*FcRnA_e2
              +(M2-(FcRn_e2+FcRnA_e2));

// FcRn-Antibody in endosome 2
dxdt_FcRnA_e2 = kon*A_e2*FcRn_e2/Ve2
                -koff*FcRnA_e2
                -krec*FcRnA_e2;

// { Endosome compartment 3 }

// Antibody in endosome 3
dxdt_A_e3 = -kon*A_e3*FcRn_e3
            +koff*FcRnA_e3*Ve3
            +krec*FcRnA_e2*Ve2;

// FcRn in endosome 3
dxdt_FcRn_e3 = -kon*A_e3*FcRn_e3/Ve3
              +koff*FcRnA_e3
              +krec*FcRnA_e3
              +(M3-(FcRn_e3+FcRnA_e3));

// FcRn-Antibody in endosome 3
dxdt_FcRnA_e3 = kon*A_e3*FcRn_e3/Ve3
              -koff*FcRnA_e3
              -krec*FcRnA_e3;

// { Fetal Blood compartment }
dxdt_A_plasma_fetal = krec*FcRnA_e3*Ve3
            - kef*A_plasma_fetal;


// calculate maternal auc
dxdt_m_auc = A_plasma/Vplasma;

// calculate fetal auc
dxdt_f_auc = A_plasma_fetal/Vplasma_fetal;

$TABLE
// Define variables of interest (post simulation calculated)
double AB_Plasma = (A_plasma)/Vplasma;
double AB_CB = (A_plasma_fetal)/Vplasma_fetal;
double f_m=AB_CB/AB_Plasma;
double FcRn_e1_total= FcRn_e1 + FcRnA_e1;
double FcRn_e2_total= FcRn_e2 + FcRnA_e2;
double FcRn_e3_total= FcRn_e3 + FcRnA_e3;


$CAPTURE AB_Plasma AB_CB GA f_m Qplacenta Vplacenta Vplasma Visf GAinitial CLupp Vplacenta_blood Vplasma_fetal FcRn_e1_total FcRn_e2_total FcRn_e3_total tad 
ETA(1) ETA(2) ETA(3) ETA(4) ETA(5) ETA(6) ETA(7) ETA(8) ETA(9) ETA(10) ETA(11) ETA(12) ETA(13) ETA(14) ETA(15) ETA(16) ETA(17) ETA(18) ETA(19) ETA(20) ETA(21)

"


Infliximab <- mcode('Infliximab_model_code', Infliximab_model_code)








## Adalimumab code




Adalimumab_model_code <- 
  
  "
$Global

$PROB
Minimal PBPK to predict the fetal exposure of adalimumab during pregnancy assuming 70 Kg weight

$PARAM @annotated
// {Physiological Parameters}
GAinitial         : 0               : GA is gestational age (weeks). GAinitial is time the simnulation to be started at in respect to pregnancy, defaulted at 0 (beginnig of the pregnancy)
TVVlymph          : 5.2             : Volume of lymph (L) 
TVL               : 2.9             : Total lymph flow (L/day) 
TVKp              : 0.8             : Fraction of interstitial space available for antibody distribution
TVRfT             : 0.945           : Vascular reflection coefficient for tight tissues
TVRfL             : 0.697           : Vascular reflection coefficient for leaky tissues
TVRflymph         : 0.2             : Lymphatic vascular reflection coefficient
TVCLm             : 0.0592          : Additional maternal clearance term for adalimumab (L/day)
TVkef             : 0.027           : Fetal clearance term for adalimumab (day-1)

// {Endosome 1 (Vascular) Parameters}
TVCLup            : 1.48            : Endothelial nonspecific pinocytosis rate (L∙day−1) 
TVCLe             : 5.75472         : Lysosome catabolism clearance (L∙day−1)
TVkrec            : 127.7193        : Endosome recycling rate constant (day−1)
TVVe1             : 0.00342         : Endosome volume for nonspecific pinocytosis (L) 
TVkon             : 20.8224         : Antibody FcRn association rate constant (nM-1.day-1) in endosomes
TVkoff            : 13996.8         : Antibody-FcRn complex (FcRnA) dissociation rate constant (day−1) in endosomes

// {PK Parameters for Adalimumab}
TVka              : 0.343          : absorption rate constant (day-1)
TVBA              : 0.64           : SC Bioavailability


$CMT @annotated //All are amounts, except for FcRn and FcRnA are concentrations:
// {Plasma Compartment}
depot             : depot compartment for SC administration
A_plasma          : Antibody in plasma
  
// {Tight Tissue Compartment}
A_Tight           : Antibody in tight tissue

// {Leaky Tissue Compartment}
A_Leaky           : Antibody in leaky tissue

// {Lymph Compartment}
A_lymph           : Antibody in lymph
  
// {Endosome 1 Compartment} 
A_e1              : Antibody in endosome 1
FcRn_e1           : FcRn endosome 1
FcRnA_e1          : FcRn-Antibody endosome 1

// {Placenta Blood} 
A_placenta_blood  : Antibody in the vascular compartment of the placenta

// {Endosome 2 Compartment - synchiotrophoblast} 
A_e2              : Antibody in endosome 2
FcRn_e2           : FcRn in endosome 2
FcRnA_e2          : FcRn-Antibody in endosome 2

// {Endosome 3 Compartment - fetal endothelial cells} 
A_e3              : Antibody in endosome 3
FcRn_e3           : FcRn in endosome 3
FcRnA_e3          : FcRn-Antibody in endosome 3

// {Fetal Blood Compartment} 
A_plasma_fetal    : Antibody in Fetal Blood


$OMEGA
0.09 // Variance for FcRn expression variability in endosomes 2 and 3
0.09
0.09
0
0
0
0
0.09
0.09
0.09
0.09
0.09
0.09
0.09
0.09
0.09
0.09
0.09
0.09
0.09
0.09
0.09
0


$MAIN 
double tad = self.tad();

// Define non-zero ODE initial conditions
FcRn_e1_0=49800; //Concentration of FcRn in endasome 1 (nM)

double GA = GAinitial + TIME/7; //GA is gestational age (weeks). GAinitial is time the simnulation to be started at in respect to pregnancy, defaulted at 0 (beginnig of the pregnancy)

//double FcRn expression equation as a variable to be included in the differential equations
if (GA < 0) double M2 = 0;
if (GA >= 0) M2 = 0.0007*exp(0.2236*GA)*exp(ETA(1))*10000*2.3;
if (GA < 0) double M3 = 0;
if (GA >= 0) M3 = 0.0007*exp(0.2236*GA)*exp(ETA(1))*10000*0.9;


// Add variabilities for fixed values
double Vlymph = TVVlymph * exp(ETA(2));
double L   =  TVL  * exp(ETA(3));   
double Kp  =  TVKp    * exp(ETA(4));   
double RfT = TVRfT  * exp(ETA(5));   
double RfL =  TVRfL   * exp(ETA(6)); 
double Rflymph =  TVRflymph   * exp(ETA(7));   
double CLm =  TVCLm      * exp(ETA(8));     
double kef = TVkef      * exp(ETA(9));   
double CLup = TVCLup    * exp(ETA(10));   
double CLe =  TVCLe    * exp(ETA(11));     
double krec =  TVkrec  * exp(ETA(12));   
double Ve1  = TVVe1  * exp(ETA(13));      
double kon  =  TVkon  * exp(ETA(14));         
double koff = TVkoff   * exp(ETA(15));
double ka = TVka   * exp(ETA(22));     
double BA = TVBA   * exp(ETA(23));   

double VisfT = Visf*0.65; //Volume of interstitial fluid/Intracellular Water in the tight tissue (L)
double VisfL = Visf*0.35; //Volume of interstitial fluid/Intracellular Water in the tight tissue (L)
double LT = L*0.33; //Lymph flow in the tight tissues (L/day)
double LL = L*0.67; //Lymph flow in the leaky tissues (L/day)

//double Vplasma: Volume of plasma (L)
if (GA < 0) double Vplasma = 2.5* exp(ETA(16));  
if (GA >= 0) Vplasma = ( 2.50 - 0.0223*GA + 0.0042*pow(GA, 2) - 0.00007*pow(GA, 3)  )*exp(ETA(16));

//double Visf: Volume of interstitial fluid/Intracellular Water (L)
if (GA < 0) double Visf = 19.81* exp(ETA(17));  
if (GA >= 0) Visf = ( 19.81 + 0.5941*GA - 0.0007*pow(GA, 2) )* exp(ETA(17));  

//double Vplacenta: Volume of placenta (L)
if (GA < 2) double Vplacenta = 0;
if (GA >= 2 & GA < 9) Vplacenta = ( (-1.7646* GA + 0.91775* pow(GA, 2) - 0.011543* pow(GA, 3))/1000 ) * exp(ETA(18)); 
if (GA >= 9) Vplacenta = ( (0.0 - 0.716* GA + 0.9149* pow(GA, 2) - 0.0122* pow(GA, 3))/1000 )* exp(ETA(18));

//double Qplacenta: Blood flow to the placenta (L/day)
if (GA <= 3.6) double Qplacenta = 0;
if (GA > 3.6)  Qplacenta = ( 0.059176 * Vplacenta * 1000 *24 )* exp(ETA(19));

//double Vplacenta_blood: Volume of placenta blood (L)
if (GA < 0) double Vplacenta_blood = 0.00001;
if (GA >= 0) Vplacenta_blood = ( 0.5*0.4*((1.9593*exp(0.1417*GA))/1000) )* exp(ETA(20)); 

//double Vplasma_fetal: Volume of the fetus blood (L)
if (GA < 0) double Vplasma_fetal = 0.00001;
if (GA >= 0) Vplasma_fetal = ( 0.5*0.6*((1.9593*exp(0.1417*GA))/1000) )* exp(ETA(21));


// {Endosome 2 (Maternal) Parameters}
//double CLupp: Endothelial nonspecific pinocytosis rate (L∙day−1) in placenta
if (GA <= 0) double CLupp = 0.001;
if (GA > 0) CLupp = ((5E-06*pow(GA, 2)) - (5E-06*GA) - 7E-05)*CLup;


//double CLep: Lysosome catabolism clearance (L∙day−1) in placental endosome
if (GA <= 0) double CLep = 0.001;
if (GA > 0) CLep = ((5E-06*pow(GA, 2)) - (5E-06*GA) - 7E-05)*CLe;


//double Ve2: Endosome volume for nonspecific pinocytosis (L) for placental endosome
double Ve2 = 0.1*1.8*((5E-06*pow(GA, 2)) - (5E-06*GA) - 7E-05)*Ve1;


// {Endosome 3 (Fetal) Parameters}
//double Ve3 Endosome volume for nonspecific pinocytosis (L) for fetal endosome
double Ve3 = 1.8*(1.428571E-05)*(-(0.0628939*pow(GA, 4)) + (6.623713*pow(GA, 3)) - (251.9597*pow(GA, 2)) + (4222.827*GA) - 26256.56)*Ve1;



$ODE 
// { Absorption compartment }
dxdt_depot = -depot*ka;

// { Plasma }

// Antibody
dxdt_A_plasma = +BA*ka*depot
                +L*A_lymph/Vlymph
                +krec*Ve1*FcRnA_e1
                -Qplacenta*A_plasma/Vplasma
                +Qplacenta*A_placenta_blood/Vplacenta_blood
                -(1-RfT)*LT*A_plasma/Vplasma
                -(1-RfL)*LL*A_plasma/Vplasma
                -CLup*A_plasma/Vplasma -CLm*A_plasma/Vplasma;
                

// { Tight tissue }

// Antibody in tight tissue
dxdt_A_Tight = (1-RfT)*LT*A_plasma/Vplasma
              -(1-Rflymph)*LT*A_Tight/(VisfT*Kp);


// { Leaky tissue }

// Antibody in leaky tissue
dxdt_A_Leaky = (1-RfL)*LL*A_plasma/Vplasma
              -(1-Rflymph)*LL*A_Leaky/(VisfL*Kp);

// { Placenta blood}
dxdt_A_placenta_blood = Qplacenta*A_plasma/Vplasma
                        -CLupp*A_placenta_blood/Vplacenta_blood
                        -Qplacenta*A_placenta_blood/Vplacenta_blood;

                        
// { Lymph }

// free antibody in lymph
dxdt_A_lymph = (1-Rflymph)*LT*A_Tight/(VisfT*Kp)
              +(1-Rflymph)*LL*A_Leaky/(VisfL*Kp)
              -L*A_lymph/Vlymph;

// { Endosome compartment 1 }

// Antibody in endosome 1
dxdt_A_e1 = -kon*A_e1*FcRn_e1
            +koff*FcRnA_e1*Ve1
            -CLe*A_e1/Ve1
            +CLup*A_plasma/Vplasma;

// FcRn in endosome 1
dxdt_FcRn_e1 = -kon*FcRn_e1*A_e1/Ve1
              +koff*FcRnA_e1
              +krec*FcRnA_e1;

// FcRn-Antibody in endosome 1
dxdt_FcRnA_e1 = kon*FcRn_e1*A_e1/Ve1
                -koff*FcRnA_e1
                -krec*FcRnA_e1;

// { Endosome compartment 2 }

// Antibody in endosome 2
dxdt_A_e2 = -kon*A_e2*FcRn_e2
            +koff*FcRnA_e2*Ve2
            -CLep*A_e2/Ve2
            +CLupp*A_placenta_blood/Vplacenta_blood;

// FcRn in endosome 2
dxdt_FcRn_e2 = -kon*A_e2*FcRn_e2/Ve2
              +koff*FcRnA_e2
              +krec*FcRnA_e2
              +(M2-(FcRn_e2+FcRnA_e2));

// FcRn-Antibody in endosome 2
dxdt_FcRnA_e2 = kon*A_e2*FcRn_e2/Ve2
                -koff*FcRnA_e2
                -krec*FcRnA_e2;

// { Endosome compartment 3 }

// Antibody in endosome 3
dxdt_A_e3 = -kon*A_e3*FcRn_e3
            +koff*FcRnA_e3*Ve3
            +krec*FcRnA_e2*Ve2;

// FcRn in endosome 3
dxdt_FcRn_e3 = -kon*A_e3*FcRn_e3/Ve3
              +koff*FcRnA_e3
              +krec*FcRnA_e3
              +(M3-(FcRn_e3+FcRnA_e3));

// FcRn-Antibody in endosome 3
dxdt_FcRnA_e3 = kon*A_e3*FcRn_e3/Ve3
              -koff*FcRnA_e3
              -krec*FcRnA_e3;

// { Fetal Blood compartment }
dxdt_A_plasma_fetal = krec*FcRnA_e3*Ve3
            - kef*A_plasma_fetal;


$TABLE
// Define variables of interest (post simulation calculated)
double AB_Plasma = (A_plasma)/Vplasma;
double AB_CB = (A_plasma_fetal)/Vplasma_fetal;
double f_m=AB_CB/AB_Plasma;
double FcRn_e1_total= FcRn_e1 + FcRnA_e1;
double FcRn_e2_total= FcRn_e2 + FcRnA_e2;
double FcRn_e3_total= FcRn_e3 + FcRnA_e3;


$CAPTURE AB_Plasma AB_CB GA f_m Qplacenta Vplacenta Vplasma Visf ka BA GAinitial CLupp Vplacenta_blood Vplasma_fetal FcRn_e1_total FcRn_e2_total FcRn_e3_total tad
ETA(1) ETA(2) ETA(3) ETA(4) ETA(5) ETA(6) ETA(7) ETA(8) ETA(9) ETA(10) ETA(11) ETA(12) ETA(13) ETA(14) ETA(15) ETA(16) ETA(17) ETA(18) ETA(19) ETA(20) ETA(21) ETA(22) ETA(23)

"


Adalimumab <- mcode('Adalimumab_model_code', Adalimumab_model_code)



## Etanercept code

Etanercept_model_code <- 
  
  "
$Global

$PROB
Minimal PBPK to predict the fetal exposure of etanercept during pregnancy assuming 70 Kg weight

$PARAM @annotated
// {Physiological Parameters}
GAinitial         : 0               : GA is gestational age (weeks). GAinitial is time the simnulation to be started at in respect to pregnancy, defaulted at 0 (beginnig of the pregnancy)
TVVlymph          : 5.2             : Volume of lymph (L) 
TVL               : 2.9             : Total lymph flow (L/day) 
TVKp              : 0.8             : Fraction of interstitial space available for antibody distribution
TVRfT             : 0.945           : Vascular reflection coefficient for tight tissues
TVRfL             : 0.697           : Vascular reflection coefficient for leaky tissues
TVRflymph         : 0.2             : Lymphatic vascular reflection coefficient
TVCLm             : 0.85            : Additional maternal clearance term for etanercept (L/day) 
TVkef             : 0.198           : Fetal clearance term for etanercept (day-1)
 
// {Endosome 1 (Vascular) Parameters}
TVCLup            : 1.48            : Endothelial nonspecific pinocytosis rate (L∙day−1) 
TVCLe             : 5.75472         : Lysosome catabolism clearance (L∙day−1)
TVkrec            : 127.7193        : Endosome recycling rate constant (day−1)
TVVe1             : 0.00342         : Endosome volume for nonspecific pinocytosis (L) 
TVkon             : 3.20544         : Antibody FcRn association rate constant (nM-1.day-1) in endosomes
TVkoff            : 11577.6         : Antibody-FcRn complex (FcRnA) dissociation rate constant (day−1) in endosomes


// {PK Parameters for etanercept}
TVka              : 0.7968   : absorption rate constant (day-1)
TVBA              : 0.58     : SC Bioavailability


$CMT @annotated //All are amounts, except for FcRn and FcRnA are concentrations:
// {Plasma Compartment}
depot             : depot compartment for SC administration
A_plasma          : Antibody in plasma
  
// {Tight Tissue Compartment}
A_Tight           : Antibody in tight tissue

// {Leaky Tissue Compartment}
A_Leaky           : Antibody in leaky tissue

// {Lymph Compartment}
A_lymph           : Antibody in lymph
  
// {Endosome 1 Compartment} 
A_e1              : Antibody in endosome 1
FcRn_e1           : FcRn endosome 1
FcRnA_e1          : FcRn-Antibody endosome 1

// {Placenta Blood} 
A_placenta_blood  : Antibody in the vascular compartment of the placenta

// {Endosome 2 Compartment - synchiotrophoblast} 
A_e2              : Antibody in endosome 2
FcRn_e2           : FcRn in endosome 2
FcRnA_e2          : FcRn-Antibody in endosome 2

// {Endosome 3 Compartment - fetal endothelial cells} 
A_e3              : Antibody in endosome 3
FcRn_e3           : FcRn in endosome 3
FcRnA_e3          : FcRn-Antibody in endosome 3

// {Fetal Blood Compartment} 
A_plasma_fetal    : Antibody in Fetal Blood


$OMEGA
0.09 // Variance for FcRn expression variability in endosomes 2 and 3
0.09
0.09
0
0
0
0
0.09
0.09
0.09
0.09
0.09
0.09
0.09
0.09
0.09
0.09
0.09
0.09
0.09
0.09
0.09
0



$MAIN 
double tad = self.tad();

// Define non-zero ODE initial conditions
FcRn_e1_0=49800; //Concentration of FcRn in endasome 1 (nM)

double GA = GAinitial + TIME/7; //GA is gestational age (weeks). GAinitial is time the simnulation to be started at in respect to pregnancy, defaulted at 0 (beginnig of the pregnancy)

//double FcRn expression equation as a variable to be included in the differential equations
if (GA < 0) double M2 = 0;
if (GA >= 0) M2 = 0.0007*exp(0.2236*GA)*exp(ETA(1))*10000*2.3;
if (GA < 0) double M3 = 0;
if (GA >= 0) M3 = 0.0007*exp(0.2236*GA)*exp(ETA(1))*10000*0.9;

// Add variabilities for fixed values
double Vlymph = TVVlymph * exp(ETA(2));
double L   =  TVL  * exp(ETA(3));   
double Kp  =  TVKp    * exp(ETA(4));   
double RfT = TVRfT  * exp(ETA(5));   
double RfL =  TVRfL   * exp(ETA(6)); 
double Rflymph =  TVRflymph   * exp(ETA(7));   
double CLm =  TVCLm      * exp(ETA(8));     
double kef = TVkef      * exp(ETA(9));   
double CLup = TVCLup    * exp(ETA(10));   
double CLe =  TVCLe    * exp(ETA(11));     
double krec =  TVkrec  * exp(ETA(12));   
double Ve1  = TVVe1  * exp(ETA(13));      
double kon  =  TVkon  * exp(ETA(14));         
double koff = TVkoff   * exp(ETA(15));
double ka = TVka   * exp(ETA(22));     
double BA = TVBA   * exp(ETA(23));

double VisfT = Visf*0.65; //Volume of interstitial fluid/Intracellular Water in the tight tissue (L)
double VisfL = Visf*0.35; //Volume of interstitial fluid/Intracellular Water in the tight tissue (L)
double LT = L*0.33; //Lymph flow in the tight tissues (L/day)
double LL = L*0.67; //Lymph flow in the leaky tissues (L/day)

//double Vplasma: Volume of plasma (L)
if (GA < 0) double Vplasma = 2.5* exp(ETA(16));  
if (GA >= 0) Vplasma = ( 2.50 - 0.0223*GA + 0.0042*pow(GA, 2) - 0.00007*pow(GA, 3)  )*exp(ETA(16));

//double Visf: Volume of interstitial fluid/Intracellular Water (L)
if (GA < 0) double Visf = 19.81* exp(ETA(17));  
if (GA >= 0) Visf = ( 19.81 + 0.5941*GA - 0.0007*pow(GA, 2) )* exp(ETA(17));  

//double Vplacenta: Volume of placenta (L)
if (GA < 2) double Vplacenta = 0;
if (GA >= 2 & GA < 9) Vplacenta = ( (-1.7646* GA + 0.91775* pow(GA, 2) - 0.011543* pow(GA, 3))/1000 ) * exp(ETA(18)); 
if (GA >= 9) Vplacenta = ( (0.0 - 0.716* GA + 0.9149* pow(GA, 2) - 0.0122* pow(GA, 3))/1000 )* exp(ETA(18));

//double Qplacenta: Blood flow to the placenta (L/day)
if (GA <= 3.6) double Qplacenta = 0;
if (GA > 3.6)  Qplacenta = ( 0.059176 * Vplacenta * 1000 *24 )* exp(ETA(19));

//double Vplacenta_blood: Volume of placenta blood (L)
if (GA < 0) double Vplacenta_blood = 0.00001;
if (GA >= 0) Vplacenta_blood = ( 0.5*0.4*((1.9593*exp(0.1417*GA))/1000) )* exp(ETA(20)); 

//double Vplasma_fetal: Volume of the fetus blood (L)
if (GA < 0) double Vplasma_fetal = 0.00001;
if (GA >= 0) Vplasma_fetal = ( 0.5*0.6*((1.9593*exp(0.1417*GA))/1000) )* exp(ETA(21));


// {Endosome 2 (Maternal) Parameters} 
//double CLupp: Endothelial nonspecific pinocytosis rate (L∙day−1) in placenta
if (GA <= 0) double CLupp = 0.001;
if (GA > 0) CLupp = ((5E-06*pow(GA, 2)) - (5E-06*GA) - 7E-05)*CLup;


//double CLep: Lysosome catabolism clearance (L∙day−1) in placental endosome
if (GA <= 0) double CLep = 0.001;
if (GA > 0) CLep = ((5E-06*pow(GA, 2)) - (5E-06*GA) - 7E-05)*CLe;


//double Ve2: Endosome volume for nonspecific pinocytosis (L) for placental endosome
double Ve2 = 0.1*1.8*((5E-06*pow(GA, 2)) - (5E-06*GA) - 7E-05)*Ve1;


// {Endosome 3 (Fetal) Parameters}
//double Ve3 Endosome volume for nonspecific pinocytosis (L) for fetal endosome
double Ve3 = 1.8*(1.428571E-05)*(-(0.0628939*pow(GA, 4)) + (6.623713*pow(GA, 3)) - (251.9597*pow(GA, 2)) + (4222.827*GA) - 26256.56)*Ve1;



$ODE 
// { Absorption compartment }
dxdt_depot = -depot*ka;

// { Plasma }

// Antibody
dxdt_A_plasma = +BA*ka*depot
                +L*A_lymph/Vlymph
                +krec*Ve1*FcRnA_e1
                -Qplacenta*A_plasma/Vplasma
                +Qplacenta*A_placenta_blood/Vplacenta_blood
                -(1-RfT)*LT*A_plasma/Vplasma
                -(1-RfL)*LL*A_plasma/Vplasma
                -CLup*A_plasma/Vplasma -CLm*A_plasma/Vplasma;
                

// { Tight tissue }

// Antibody in tight tissue
dxdt_A_Tight = (1-RfT)*LT*A_plasma/Vplasma
              -(1-Rflymph)*LT*A_Tight/(VisfT*Kp);


// { Leaky tissue }

// Antibody in leaky tissue
dxdt_A_Leaky = (1-RfL)*LL*A_plasma/Vplasma
              -(1-Rflymph)*LL*A_Leaky/(VisfL*Kp);

// { Placenta blood}
dxdt_A_placenta_blood = Qplacenta*A_plasma/Vplasma
                        -CLupp*A_placenta_blood/Vplacenta_blood
                        -Qplacenta*A_placenta_blood/Vplacenta_blood;

                        
// { Lymph }

// free antibody in lymph
dxdt_A_lymph = (1-Rflymph)*LT*A_Tight/(VisfT*Kp)
              +(1-Rflymph)*LL*A_Leaky/(VisfL*Kp)
              -L*A_lymph/Vlymph;

// { Endosome compartment 1 }

// Antibody in endosome 1
dxdt_A_e1 = -kon*A_e1*FcRn_e1
            +koff*FcRnA_e1*Ve1
            -CLe*A_e1/Ve1
            +CLup*A_plasma/Vplasma;

// FcRn in endosome 1
dxdt_FcRn_e1 = -kon*FcRn_e1*A_e1/Ve1
              +koff*FcRnA_e1
              +krec*FcRnA_e1;

// FcRn-Antibody in endosome 1
dxdt_FcRnA_e1 = kon*FcRn_e1*A_e1/Ve1
                -koff*FcRnA_e1
                -krec*FcRnA_e1;

// { Endosome compartment 2 }

// Antibody in endosome 2
dxdt_A_e2 = -kon*A_e2*FcRn_e2
            +koff*FcRnA_e2*Ve2
            -CLep*A_e2/Ve2
            +CLupp*A_placenta_blood/Vplacenta_blood;

// FcRn in endosome 2
dxdt_FcRn_e2 = -kon*A_e2*FcRn_e2/Ve2
              +koff*FcRnA_e2
              +krec*FcRnA_e2
              +(M2-(FcRn_e2+FcRnA_e2));

// FcRn-Antibody in endosome 2
dxdt_FcRnA_e2 = kon*A_e2*FcRn_e2/Ve2
                -koff*FcRnA_e2
                -krec*FcRnA_e2;

// { Endosome compartment 3 }

// Antibody in endosome 3
dxdt_A_e3 = -kon*A_e3*FcRn_e3
            +koff*FcRnA_e3*Ve3
            +krec*FcRnA_e2*Ve2;

// FcRn in endosome 3
dxdt_FcRn_e3 = -kon*A_e3*FcRn_e3/Ve3
              +koff*FcRnA_e3
              +krec*FcRnA_e3
              +(M3-(FcRn_e3+FcRnA_e3));

// FcRn-Antibody in endosome 3
dxdt_FcRnA_e3 = kon*A_e3*FcRn_e3/Ve3
              -koff*FcRnA_e3
              -krec*FcRnA_e3;

// { Fetal Blood compartment }
dxdt_A_plasma_fetal = krec*FcRnA_e3*Ve3
            -kef*A_plasma_fetal;


$TABLE
// Define variables of interest (post simulation calculated)
double AB_Plasma = (A_plasma)/Vplasma;
double AB_CB = (A_plasma_fetal)/Vplasma_fetal;
double f_m=AB_CB/AB_Plasma;
double FcRn_e1_total= FcRn_e1 + FcRnA_e1;
double FcRn_e2_total= FcRn_e2 + FcRnA_e2;
double FcRn_e3_total= FcRn_e3 + FcRnA_e3;


$CAPTURE AB_Plasma AB_CB GA f_m Qplacenta Vplacenta Vplasma Visf ka BA GAinitial CLupp Vplacenta_blood Vplasma_fetal FcRn_e1_total FcRn_e2_total FcRn_e3_total tad
ETA(1) ETA(2) ETA(3) ETA(4) ETA(5) ETA(6) ETA(7) ETA(8) ETA(9) ETA(10) ETA(11) ETA(12) ETA(13) ETA(14) ETA(15) ETA(16) ETA(17) ETA(18) ETA(19) ETA(20) ETA(21) ETA(22) ETA(23)

"


Etanercept <- mcode('Etanercept_model_code', Etanercept_model_code)



## Ustekinumab code


Ustekinumab_model_code <- 
  
  "
$Global

$PROB
Minimal PBPK to predict the fetal exposure of ustekinumab during pregnancy assuming 70 Kg weight

$PARAM @annotated
// {Physiological Parameters}
GAinitial         : 0               : GA is gestational age (weeks). GAinitial is time the simnulation to be started at in respect to pregnancy, defaulted at 0 (beginnig of the pregnancy)
TVVlymph          : 5.2             : Volume of lymph (L) 
TVL               : 2.9             : Total lymph flow (L/day) 
TVKp              : 0.8             : Fraction of interstitial space available for antibody distribution
TVRfT             : 0.945           : Vascular reflection coefficient for tight tissues
TVRfL             : 0.697           : Vascular reflection coefficient for leaky tissues
TVRflymph         : 0.2             : Lymphatic vascular reflection coefficient
TVkef             : 0.030           : Fetal clearance term for ustekinumab (day-1)
  
// {Endosome 1 (Vascular) Parameters}
TVCLup            : 1.48            : Endothelial nonspecific pinocytosis rate (L∙day−1) 
TVCLe             : 5.75472         : Lysosome catabolism clearance (L∙day−1)
TVkrec            : 127.7193        : Endosome recycling rate constant (day−1)
TVVe1             : 0.00342         : Endosome volume for nonspecific pinocytosis (L) 
TVkon             : 12.096          : Antibody FcRn association rate constant (nM-1.day-1) in endosomes
TVkoff            : 8640            : Antibody-FcRn complex (FcRnA) dissociation rate constant (day−1) in endosomes
disease           : 0               : Disease=0 Ulcerative Colitis (UC), Disease=1 Crohn's Disease (CD)

// {PK Parameters for Ustekinumab} //See disease specific parameters below in $Main
//ka              :           : absorption rate constant (day-1)
//BA              :           : SC Bioavailability


$CMT @annotated //All are amounts, except for FcRn and FcRnA are concentrations:
// {Plasma Compartment}
depot             : depot compartment for SC administration
A_plasma          : Antibody in plasma
  
// {Tight Tissue Compartment}
A_Tight           : Antibody in tight tissue

// {Leaky Tissue Compartment}
A_Leaky           : Antibody in leaky tissue

// {Lymph Compartment}
A_lymph           : Antibody in lymph
  
// {Endosome 1 Compartment} 
A_e1              : Antibody in endosome 1
FcRn_e1           : FcRn endosome 1
FcRnA_e1          : FcRn-Antibody endosome 1

// {Placenta Blood} 
A_placenta_blood  : Antibody in the vascular compartment of the placenta

// {Endosome 2 Compartment - synchiotrophoblast} 
A_e2              : Antibody in endosome 2
FcRn_e2           : FcRn in endosome 2
FcRnA_e2          : FcRn-Antibody in endosome 2

// {Endosome 3 Compartment - fetal endothelial cells} 
A_e3              : Antibody in endosome 3
FcRn_e3           : FcRn in endosome 3
FcRnA_e3          : FcRn-Antibody in endosome 3

// {Fetal Blood Compartment} 
A_plasma_fetal    : Antibody in Fetal Blood


$OMEGA
0.09 // Variance for FcRn expression variability in endosomes 2 and 3
0.09
0.09
0
0
0
0
0.09
0.09
0.09
0.09
0.09
0.09
0.09
0.09
0.09
0.09
0.09
0.09
0.09
0.09
0


$MAIN
double tad = self.tad();

// Define non-zero ODE initial conditions
FcRn_e1_0=49800; //Concentration of FcRn in endasome 1 (nM)

double GA = GAinitial + TIME/7; //GA is gestational age (weeks). GAinitial is time the simnulation to be started at in respect to pregnancy, defaulted at 0 (beginnig of the pregnancy)

//double FcRn expression equation as a variable to be included in the differential equations
if (GA < 0) double M2 = 0;
if (GA >= 0) M2 = 0.0007*exp(0.2236*GA)*exp(ETA(1))*10000*2.3;
if (GA < 0) double M3 = 0;
if (GA >= 0) M3 = 0.0007*exp(0.2236*GA)*exp(ETA(1))*10000*0.9;



// {PK Parameters for Ustekinumab}
if (disease==0) double TVka = 0.142; //absorption rate constant (day-1) for UC
else if (disease==1) TVka = 0.181; //absorption rate constant (day-1) for CD

if (disease==0) double TVBA = 0.872; //SC Bioavailability for UC
else if (disease==1) TVBA = 0.78; //SC Bioavailability for CD


// Add variabilities for fixed values
double Vlymph = TVVlymph * exp(ETA(2));
double L   =  TVL  * exp(ETA(3));   
double Kp  =  TVKp    * exp(ETA(4));   
double RfT = TVRfT  * exp(ETA(5));   
double RfL =  TVRfL   * exp(ETA(6)); 
double Rflymph =  TVRflymph   * exp(ETA(7));   
double kef = TVkef      * exp(ETA(8));   
double CLup = TVCLup    * exp(ETA(9));   
double CLe =  TVCLe    * exp(ETA(10));     
double krec =  TVkrec  * exp(ETA(11));   
double Ve1  = TVVe1  * exp(ETA(12));      
double kon  =  TVkon  * exp(ETA(13));         
double koff = TVkoff   * exp(ETA(14));
double ka = TVka   * exp(ETA(21));     
double BA = TVBA   * exp(ETA(22));   



double VisfT = Visf*0.65; //Volume of interstitial fluid/Intracellular Water in the tight tissue (L)
double VisfL = Visf*0.35; //Volume of interstitial fluid/Intracellular Water in the tight tissue (L)
double LT = L*0.33; //Lymph flow in the tight tissues (L/day)
double LL = L*0.67; //Lymph flow in the leaky tissues (L/day)

//double Vplasma: Volume of plasma (L)
if (GA < 0) double Vplasma = 2.5* exp(ETA(15));  
if (GA >= 0) Vplasma = ( 2.50 - 0.0223*GA + 0.0042*pow(GA, 2) - 0.00007*pow(GA, 3)  )*exp(ETA(15));

//double Visf: Volume of interstitial fluid/Intracellular Water (L)
if (GA < 0) double Visf = 19.81* exp(ETA(16));  
if (GA >= 0) Visf = ( 19.81 + 0.5941*GA - 0.0007*pow(GA, 2) )* exp(ETA(16));  

//double Vplacenta: Volume of placenta (L)
if (GA < 2) double Vplacenta = 0;
if (GA >= 2 & GA < 9) Vplacenta = ( (-1.7646* GA + 0.91775* pow(GA, 2) - 0.011543* pow(GA, 3))/1000 ) * exp(ETA(17)); 
if (GA >= 9) Vplacenta = ( (0.0 - 0.716* GA + 0.9149* pow(GA, 2) - 0.0122* pow(GA, 3))/1000 )* exp(ETA(17));

//double Qplacenta: Blood flow to the placenta (L/day)
if (GA <= 3.6) double Qplacenta = 0;
if (GA > 3.6)  Qplacenta = ( 0.059176 * Vplacenta * 1000 *24 )* exp(ETA(18));

//double Vplacenta_blood: Volume of placenta blood (L)
if (GA < 0) double Vplacenta_blood = 0.00001;
if (GA >= 0) Vplacenta_blood = ( 0.5*0.4*((1.9593*exp(0.1417*GA))/1000) )* exp(ETA(19)); 

//double Vplasma_fetal: Volume of the fetus blood (L)
if (GA < 0) double Vplasma_fetal = 0.00001;
if (GA >= 0) Vplasma_fetal = ( 0.5*0.6*((1.9593*exp(0.1417*GA))/1000) )* exp(ETA(20));


// {Endosome 2 (Maternal) Parameters}
//double CLupp: Endothelial nonspecific pinocytosis rate (L∙day−1) in placenta
if (GA <= 0) double CLupp = 0.001;
if (GA > 0) CLupp = ((5E-06*pow(GA, 2)) - (5E-06*GA) - 7E-05)*CLup;


//double CLep: Lysosome catabolism clearance (L∙day−1) in placental endosome
if (GA <= 0) double CLep = 0.001;
if (GA > 0) CLep = ((5E-06*pow(GA, 2)) - (5E-06*GA) - 7E-05)*CLe;


//double Ve2: Endosome volume for nonspecific pinocytosis (L) for placental endosome
double Ve2 = 0.1*1.8*((5E-06*pow(GA, 2)) - (5E-06*GA) - 7E-05)*Ve1;


// {Endosome 3 (Fetal) Parameters}
//double Ve3 Endosome volume for nonspecific pinocytosis (L) for fetal endosome
double Ve3 = 1.8*(1.428571E-05)*(-(0.0628939*pow(GA, 4)) + (6.623713*pow(GA, 3)) - (251.9597*pow(GA, 2)) + (4222.827*GA) - 26256.56)*Ve1;




$ODE 
// { Absorption compartment }
dxdt_depot = -depot*ka;

// { Plasma }

// Antibody
dxdt_A_plasma = +BA*ka*depot
                +L*A_lymph/Vlymph
                +krec*Ve1*FcRnA_e1
                -Qplacenta*A_plasma/Vplasma
                +Qplacenta*A_placenta_blood/Vplacenta_blood
                -(1-RfT)*LT*A_plasma/Vplasma
                -(1-RfL)*LL*A_plasma/Vplasma
                -CLup*A_plasma/Vplasma;
                

// { Tight tissue }

// Antibody in tight tissue
dxdt_A_Tight = (1-RfT)*LT*A_plasma/Vplasma
              -(1-Rflymph)*LT*A_Tight/(VisfT*Kp);


// { Leaky tissue }

// Antibody in leaky tissue
dxdt_A_Leaky = (1-RfL)*LL*A_plasma/Vplasma
              -(1-Rflymph)*LL*A_Leaky/(VisfL*Kp);

// { Placenta blood}
dxdt_A_placenta_blood = Qplacenta*A_plasma/Vplasma
                        -CLupp*A_placenta_blood/Vplacenta_blood
                        -Qplacenta*A_placenta_blood/Vplacenta_blood;

                        
// { Lymph }

// free antibody in lymph
dxdt_A_lymph = (1-Rflymph)*LT*A_Tight/(VisfT*Kp)
              +(1-Rflymph)*LL*A_Leaky/(VisfL*Kp)
              -L*A_lymph/Vlymph;

// { Endosome compartment 1 }

// Antibody in endosome 1
dxdt_A_e1 = -kon*A_e1*FcRn_e1
            +koff*FcRnA_e1*Ve1
            -CLe*A_e1/Ve1
            +CLup*A_plasma/Vplasma;

// FcRn in endosome 1
dxdt_FcRn_e1 = -kon*FcRn_e1*A_e1/Ve1
              +koff*FcRnA_e1
              +krec*FcRnA_e1;

// FcRn-Antibody in endosome 1
dxdt_FcRnA_e1 = kon*FcRn_e1*A_e1/Ve1
                -koff*FcRnA_e1
                -krec*FcRnA_e1;

// { Endosome compartment 2 }

// Antibody in endosome 2
dxdt_A_e2 = -kon*A_e2*FcRn_e2
            +koff*FcRnA_e2*Ve2
            -CLep*A_e2/Ve2
            +CLupp*A_placenta_blood/Vplacenta_blood;

// FcRn in endosome 2
dxdt_FcRn_e2 = -kon*A_e2*FcRn_e2/Ve2
              +koff*FcRnA_e2
              +krec*FcRnA_e2
              +(M2-(FcRn_e2+FcRnA_e2));

// FcRn-Antibody in endosome 2
dxdt_FcRnA_e2 = kon*A_e2*FcRn_e2/Ve2
                -koff*FcRnA_e2
                -krec*FcRnA_e2;

// { Endosome compartment 3 }

// Antibody in endosome 3
dxdt_A_e3 = -kon*A_e3*FcRn_e3
            +koff*FcRnA_e3*Ve3
            +krec*FcRnA_e2*Ve2;

// FcRn in endosome 3
dxdt_FcRn_e3 = -kon*A_e3*FcRn_e3/Ve3
              +koff*FcRnA_e3
              +krec*FcRnA_e3
              +(M3-(FcRn_e3+FcRnA_e3));

// FcRn-Antibody in endosome 3
dxdt_FcRnA_e3 = kon*A_e3*FcRn_e3/Ve3
              -koff*FcRnA_e3
              -krec*FcRnA_e3;

// { Fetal Blood compartment }
dxdt_A_plasma_fetal = krec*FcRnA_e3*Ve3
            - kef*A_plasma_fetal;


$TABLE
// Define variables of interest (post simulation calculated)
double AB_Plasma = (A_plasma)/Vplasma;
double AB_CB = (A_plasma_fetal)/Vplasma_fetal;
double f_m=AB_CB/AB_Plasma;
double FcRn_e1_total= FcRn_e1 + FcRnA_e1;
double FcRn_e2_total= FcRn_e2 + FcRnA_e2;
double FcRn_e3_total= FcRn_e3 + FcRnA_e3;


$CAPTURE AB_Plasma AB_CB GA f_m Qplacenta Vplacenta Vplasma Visf ka BA GAinitial CLupp Vplacenta_blood Vplasma_fetal FcRn_e1_total FcRn_e2_total FcRn_e3_total tad
ETA(1) ETA(2) ETA(3) ETA(4) ETA(5) ETA(6) ETA(7) ETA(8) ETA(9) ETA(10) ETA(11) ETA(12) ETA(13) ETA(14) ETA(15) ETA(16) ETA(17) ETA(18) ETA(19) ETA(20) ETA(21) ETA(22)

"


Ustekinumab <- mcode('Ustekinumab_model_code', Ustekinumab_model_code)





## Vedolizumab code


Vedolizumab_model_code <- 
  
  "
$Global

$PROB
Minimal PBPK to predict the fetal exposure of vedolizumab during pregnancy assuming 70 Kg weight

$PARAM @annotated
// {Physiological Parameters}
GAinitial         : 0               : GA is gestational age (weeks). GAinitial is time the simnulation to be started at in respect to pregnancy, defaulted at 0 (beginnig of the pregnancy)
TVVlymph          : 5.2             : Volume of lymph (L) 
TVL               : 2.9             : Total lymph flow (L/day) 
TVKp              : 0.8             : Fraction of interstitial space available for antibody distribution
TVRfT             : 0.945           : Vascular reflection coefficient for tight tissues
TVRfL             : 0.697           : Vascular reflection coefficient for leaky tissues
TVRflymph         : 0.2             : Lymphatic vascular reflection coefficient
TVkef             : 0.1             : Fetal clearance term for vedolizumab (day-1)
TVKm              : 6.566757        : Additional maternal non-linear clearance. Km is concentration at half-maximum elimination rate (nM)
TVVmax            : 1.805177        : Additional maternal non-linear clearance. Vmax is maximum elimination rate (nmoles/day)
  
// {Endosome 1 (Vascular) Parameters}
TVCLup            : 1.48            : Endothelial nonspecific pinocytosis rate (L∙day−1) 
TVCLe             : 5.75472         : Lysosome catabolism clearance (L∙day−1)
TVkrec            : 127.7193        : Endosome recycling rate constant (day−1)
TVVe1             : 0.00342         : Endosome volume for nonspecific pinocytosis (L) 
TVkon             : 20.8224         : Antibody FcRn association rate constant (nM-1.day-1) in endosomes
TVkoff            : 13996.8         : Antibody-FcRn complex (FcRnA) dissociation rate constant (day−1) in endosomes


// {PK Parameters}
//ka              :            : absorption rate constant (day-1)
//BA              :            : SC Bioavailability


$CMT @annotated //All are amounts, except for FcRn and FcRnA are concentrations:
// {Plasma Compartment}
depot             : depot compartment for SC administration
A_plasma          : Antibody in plasma
m_auc             : Maternal AUC
  
// {Tight Tissue Compartment}
A_Tight           : Antibody in tight tissue

// {Leaky Tissue Compartment}
A_Leaky           : Antibody in leaky tissue

// {Lymph Compartment}
A_lymph           : Antibody in lymph
  
// {Endosome 1 Compartment} 
A_e1              : Antibody in endosome 1
FcRn_e1           : FcRn endosome 1
FcRnA_e1          : FcRn-Antibody endosome 1

// {Placenta Blood} 
A_placenta_blood  : Antibody in the vascular compartment of the placenta

// {Endosome 2 Compartment - synchiotrophoblast} 
A_e2              : Antibody in endosome 2
FcRn_e2           : FcRn in endosome 2
FcRnA_e2          : FcRn-Antibody in endosome 2

// {Endosome 3 Compartment - fetal endothelial cells} 
A_e3              : Antibody in endosome 3
FcRn_e3           : FcRn in endosome 3
FcRnA_e3          : FcRn-Antibody in endosome 3

// {Fetal Blood Compartment} 
A_plasma_fetal    : Antibody in Fetal Blood
f_auc             : Fetal AUC

$OMEGA
0.09 // Variance for FcRn expression variability in endosomes 2 and 3
0.09
0.09
0
0
0
0
0.09
0.09
0.09
0.09
0.09
0.09
0.09
0.09
0.09
0.09
0.09
0.09
0.09
0.09
0.09


$MAIN 
double tad = self.tad();

// Define non-zero ODE initial conditions
FcRn_e1_0=49800; //Concentration of FcRn in endasome 1 (nM)

double GA = GAinitial + TIME/7; //GA is gestational age (weeks). GAinitial is time the simnulation to be started at in respect to pregnancy, defaulted at 0 (beginnig of the pregnancy)

//double FcRn expression equation as a variable to be included in the differential equations
if (GA < 0) double M2 = 0;
if (GA >= 0) M2 = 0.0007*exp(0.2236*GA)*exp(ETA(1))*10000*2.3;
if (GA < 0) double M3 = 0;
if (GA >= 0) M3 = 0.0007*exp(0.2236*GA)*exp(ETA(1))*10000*0.9;


// Add variabilities for fixed values
double Vlymph = TVVlymph * exp(ETA(2));
double L   =  TVL  * exp(ETA(3));   
double Kp  =  TVKp    * exp(ETA(4));   
double RfT = TVRfT  * exp(ETA(5));   
double RfL =  TVRfL   * exp(ETA(6)); 
double Rflymph =  TVRflymph   * exp(ETA(7));   
double kef = TVkef      * exp(ETA(8));   
double CLup = TVCLup    * exp(ETA(9));   
double CLe =  TVCLe    * exp(ETA(10));     
double krec =  TVkrec  * exp(ETA(11));   
double Ve1  = TVVe1  * exp(ETA(12));      
double kon  =  TVkon  * exp(ETA(13));         
double koff = TVkoff   * exp(ETA(14));
double Km = TVKm      * exp(ETA(21));   
double Vmax = TVVmax      * exp(ETA(22));   


double VisfT = Visf*0.65; //Volume of interstitial fluid/Intracellular Water in the tight tissue (L)
double VisfL = Visf*0.35; //Volume of interstitial fluid/Intracellular Water in the tight tissue (L)
double LT = L*0.33; //Lymph flow in the tight tissues (L/day)
double LL = L*0.67; //Lymph flow in the leaky tissues (L/day)

//double Vplasma: Volume of plasma (L)
if (GA < 0) double Vplasma = 2.5* exp(ETA(15));  
if (GA >= 0) Vplasma = ( 2.50 - 0.0223*GA + 0.0042*pow(GA, 2) - 0.00007*pow(GA, 3)  )*exp(ETA(15));

//double Visf: Volume of interstitial fluid/Intracellular Water (L)
if (GA < 0) double Visf = 19.81* exp(ETA(16));  
if (GA >= 0) Visf = ( 19.81 + 0.5941*GA - 0.0007*pow(GA, 2) )* exp(ETA(16));  

//double Vplacenta: Volume of placenta (L)
if (GA < 2) double Vplacenta = 0;
if (GA >= 2 & GA < 9) Vplacenta = ( (-1.7646* GA + 0.91775* pow(GA, 2) - 0.011543* pow(GA, 3))/1000 ) * exp(ETA(17)); 
if (GA >= 9) Vplacenta = ( (0.0 - 0.716* GA + 0.9149* pow(GA, 2) - 0.0122* pow(GA, 3))/1000 )* exp(ETA(17));

//double Qplacenta: Blood flow to the placenta (L/day)
if (GA <= 3.6) double Qplacenta = 0;
if (GA > 3.6)  Qplacenta = ( 0.059176 * Vplacenta * 1000 *24 )* exp(ETA(18));

//double Vplacenta_blood: Volume of placenta blood (L)
if (GA < 0) double Vplacenta_blood = 0.00001;
if (GA >= 0) Vplacenta_blood = ( 0.5*0.4*((1.9593*exp(0.1417*GA))/1000) )* exp(ETA(19)); 

//double Vplasma_fetal: Volume of the fetus blood (L)
if (GA < 0) double Vplasma_fetal = 0.00001;
if (GA >= 0) Vplasma_fetal = ( 0.5*0.6*((1.9593*exp(0.1417*GA))/1000) )* exp(ETA(20));


// {Endosome 2 (Maternal) Parameters}
//double CLupp: Endothelial nonspecific pinocytosis rate (L∙day−1) in placenta
if (GA <= 0) double CLupp = 0.001;
if (GA > 0) CLupp = ((5E-06*pow(GA, 2)) - (5E-06*GA) - 7E-05)*CLup;


//double CLep: Lysosome catabolism clearance (L∙day−1) in placental endosome
if (GA <= 0) double CLep = 0.001;
if (GA > 0) CLep = ((5E-06*pow(GA, 2)) - (5E-06*GA) - 7E-05)*CLe;


//double Ve2: Endosome volume for nonspecific pinocytosis (L) for placental endosome
double Ve2 = 0.1*1.8*((5E-06*pow(GA, 2)) - (5E-06*GA) - 7E-05)*Ve1;


// {Endosome 3 (Fetal) Parameters}
//double Ve3 Endosome volume for nonspecific pinocytosis (L) for fetal endosome
double Ve3 = 1.8*(1.428571E-05)*(-(0.0628939*pow(GA, 4)) + (6.623713*pow(GA, 3)) - (251.9597*pow(GA, 2)) + (4222.827*GA) - 26256.56)*Ve1;



$ODE 
// { Absorption compartment }
//dxdt_depot = -depot*ka;

// { Plasma }

// Antibody
dxdt_A_plasma = +L*A_lymph/Vlymph
                +krec*Ve1*FcRnA_e1
                -Qplacenta*A_plasma/Vplasma
                +Qplacenta*A_placenta_blood/Vplacenta_blood
                -(1-RfT)*LT*A_plasma/Vplasma
                -(1-RfL)*LL*A_plasma/Vplasma
                -CLup*A_plasma/Vplasma - ( (Vmax/(Km+(A_plasma/Vplasma))) * (A_plasma/Vplasma) ) ;
                

// { Tight tissue }

// Antibody in tight tissue
dxdt_A_Tight = (1-RfT)*LT*A_plasma/Vplasma
              -(1-Rflymph)*LT*A_Tight/(VisfT*Kp);


// { Leaky tissue }

// Antibody in leaky tissue
dxdt_A_Leaky = (1-RfL)*LL*A_plasma/Vplasma
              -(1-Rflymph)*LL*A_Leaky/(VisfL*Kp);

// { Placenta blood}
dxdt_A_placenta_blood = Qplacenta*A_plasma/Vplasma
                        -CLupp*A_placenta_blood/Vplacenta_blood
                        -Qplacenta*A_placenta_blood/Vplacenta_blood;
                        

// { Lymph }

// free antibody in lymph
dxdt_A_lymph = (1-Rflymph)*LT*A_Tight/(VisfT*Kp)
              +(1-Rflymph)*LL*A_Leaky/(VisfL*Kp)
              -L*A_lymph/Vlymph;

// { Endosome compartment 1 }

// Antibody in endosome 1
dxdt_A_e1 = -kon*A_e1*FcRn_e1
            +koff*FcRnA_e1*Ve1
            -CLe*A_e1/Ve1
            +CLup*A_plasma/Vplasma;

// FcRn in endosome 1
dxdt_FcRn_e1 = -kon*FcRn_e1*A_e1/Ve1
              +koff*FcRnA_e1
              +krec*FcRnA_e1;

// FcRn-Antibody in endosome 1
dxdt_FcRnA_e1 = kon*FcRn_e1*A_e1/Ve1
                -koff*FcRnA_e1
                -krec*FcRnA_e1;

// { Endosome compartment 2 }

// Antibody in endosome 2
dxdt_A_e2 = -kon*A_e2*FcRn_e2
            +koff*FcRnA_e2*Ve2
            -CLep*A_e2/Ve2
            +CLupp*A_placenta_blood/Vplacenta_blood;

// FcRn in endosome 2
dxdt_FcRn_e2 = -kon*A_e2*FcRn_e2/Ve2
              +koff*FcRnA_e2
              +krec*FcRnA_e2
              +(M2-(FcRn_e2+FcRnA_e2));

// FcRn-Antibody in endosome 2
dxdt_FcRnA_e2 = kon*A_e2*FcRn_e2/Ve2
                -koff*FcRnA_e2
                -krec*FcRnA_e2;

// { Endosome compartment 3 }

// Antibody in endosome 3
dxdt_A_e3 = -kon*A_e3*FcRn_e3
            +koff*FcRnA_e3*Ve3
            +krec*FcRnA_e2*Ve2;

// FcRn in endosome 3
dxdt_FcRn_e3 = -kon*A_e3*FcRn_e3/Ve3
              +koff*FcRnA_e3
              +krec*FcRnA_e3
              +(M3-(FcRn_e3+FcRnA_e3));

// FcRn-Antibody in endosome 3
dxdt_FcRnA_e3 = kon*A_e3*FcRn_e3/Ve3
              -koff*FcRnA_e3
              -krec*FcRnA_e3;

// { Fetal Blood compartment }
dxdt_A_plasma_fetal = krec*FcRnA_e3*Ve3
            - kef*A_plasma_fetal;


// calculate maternal auc
dxdt_m_auc = A_plasma/Vplasma;

// calculate fetal auc
dxdt_f_auc = A_plasma_fetal/Vplasma_fetal;

$TABLE
// Define variables of interest (post simulation calculated)
double AB_Plasma = (A_plasma)/Vplasma;
double AB_CB = (A_plasma_fetal)/Vplasma_fetal;
double f_m=AB_CB/AB_Plasma;
double FcRn_e1_total= FcRn_e1 + FcRnA_e1;
double FcRn_e2_total= FcRn_e2 + FcRnA_e2;
double FcRn_e3_total= FcRn_e3 + FcRnA_e3;


$CAPTURE AB_Plasma AB_CB GA f_m Qplacenta Vplacenta Vplasma Visf GAinitial CLupp Vplacenta_blood Vplasma_fetal FcRn_e1_total FcRn_e2_total FcRn_e3_total tad
ETA(1) ETA(2) ETA(3) ETA(4) ETA(5) ETA(6) ETA(7) ETA(8) ETA(9) ETA(10) ETA(11) ETA(12) ETA(13) ETA(14) ETA(15) ETA(16) ETA(17) ETA(18) ETA(19) ETA(20) ETA(21) ETA(22)

"


Vedolizumab <- mcode('Vedolizumab_model_code', Vedolizumab_model_code)




# Shiny Application Code

# Available models
available_models <- c("Infliximab", "Adalimumab", "Etanercept", "Ustekinumab", "Vedolizumab")

# VPC simulation function
vpcsim <- function(rep, data, model, mw, recover = "dose, Delivery, disease, pregnancy, ID_new, Drug") {
  ans <- mrgsim(
    model,
    data = data,
    recover = recover,
    output = 'df',
    delta = data$delta[1],
    end = data$end[1],
    atol = 1E-2
  ) %>%
    mutate(
      irep = rep,
      conc_m = ((AB_Plasma * mw) / 1000000000) * 1000,
      conc_f = ((AB_CB * mw) / 1000000000) * 1000,
      week = time / 7,
      tad_week = tad / 7,
      pregnancy_week = pregnancy / 7
    )
  return(ans)
}

# Define UI for the Shiny app
ui <- fluidPage(
  tags$style(HTML("
    #bottomRightText {
      position: fixed;
      bottom: 60px;
      left: 500px;
      font-size: 12px;
      color: black;
      background-color: white;
      padding: 5px;
      border-radius: 3px;
      box-shadow: 0 0 10px rgba(0,0,0,0.1);
    }

  ")),
  
  titlePanel("Simulate from Antibodies mPBPK Pregnancy Model"),
  
  sidebarLayout(
    sidebarPanel(
      width = 3,
      selectInput("model_select", "Select Model:", choices = available_models),
      radioButtons("regimen_type", "Regimen Type:", choices = c("Consistent", "Custom")),
      
      # Consistent Regimen Inputs
      conditionalPanel(
        condition = "input.regimen_type == 'Consistent'",
        numericInput("amt", "Dose amount (mg):", value = 350, min = 0),
        numericInput("ii", "Dosing Interval (days):", value = 56 , min = 1),
        numericInput("addl", "Number of Additional Doses:", value = 6, min = 0),
        #selectInput("admin_route", "Administration Route:", choices = c("IV" = "IV", "SC" = "SC"))
      ),
      
      # Custom Regimen Inputs
      conditionalPanel(
        condition = "input.regimen_type == 'Custom'",
        numericInput("num_events", "Number of Dosing Events:", value = 1, min = 1),
        uiOutput("custom_event_inputs")  # Placeholder for dynamic inputs
      ),
      
      # Custom Model Inputs
      conditionalPanel(
        condition = "input.model_select == 'Ustekinumab'",
        selectInput("disease", "Disease:", choices = c("Ulcerative colitis" = "Ulcerative colitis", "Crohn's disease" = "Crohn's disease"))
      ),
      
      # Custom Model Inputs
      conditionalPanel(
        condition = "input.model_select == 'Infliximab' | input.model_select == 'Vedolizumab'",
        selectInput("admin_route", "Administration Route:", choices = c("IV" = "IV"))
      ),
      
      conditionalPanel(
        condition = "input.model_select == 'Adalimumab' | input.model_select == 'Etanercept' | input.model_select == 'Ustekinumab'",
        selectInput("admin_route", "Administration Route:", choices = c("IV" = "IV", "SC" = "SC"))
      ),
      
      # Common Inputs
      numericInput("GAinitial", "Gestational age at start of simulation (weeks):", value = 0, min = -500),
      numericInput("Delivery", "Expected delivery week (weeks):", value = 40, min = 1),
      #numericInput("end", "Simulation end time (days):", value = 343, min = 1),
      numericInput("delta", "Simulation sampling interval (days):", value = 7, min = 0.1),
      #numericInput("mw", "Molecular weight (dalton)", value = 149000, min = 1),
      numericInput("efficacy", "Maternal efficacy threshold (μg/mL):", value = 5),
      numericInput("toxicity", "Fetal toxicity threshold (μg/mL):", value = 20),
      numericInput("n_vp", "Number of Virtual Patients:", value = 10, min = 1),
      actionButton("simulate", "Run Simulation")
    ),
    
    mainPanel(
      width = 9,
      fluidRow(
        column(12, plotOutput("conc_plot", height = "500px"))
      ),
      uiOutput("download_button_ui")
    )
  ),
  
  div(id = "bottomRightText", 
  "This software is intended for research and exploratory analysis only.
  It should not be used for clinical decision-making, diagnosis, treatment, or patient management 
  before any prospective clinical validations. The results generated by this tool are for informational purposes only.
  The developers assume no responsibility or liability for any outcomes resulting from the use of this R Shiny code.")
  
)

# Define server logic for the Shiny app
server <- function(input, output, session) {
  
  # Define simulation_output as a reactiveVal to store the simulation results
  simulation_output <- reactiveVal()
  
  # Generate custom event input fields based on the number of events after custom regimen is selected
  output$custom_event_inputs <- renderUI({
    num_events <- input$num_events
    event_ui <- lapply(1:num_events, function(i) {
      tagList(
        h4(paste("Event", i)),
        numericInput(paste0("amt_", i), "Dose (mg):", value = 0, min = 0),
        numericInput(paste0("ii_", i), "Interval (days):", value = 1, min = 0),
        numericInput(paste0("addl_", i), "Addl. Doses:", value = 0, min = 0),
        #selectInput(paste0("cmt_", i), "Route:", choices = c("IV" = "IV", "SC" = "SC")),
        
        conditionalPanel(
          condition = "input.model_select == 'Infliximab' | input.model_select == 'Vedolizumab'",
          selectInput(paste0("cmt_", i), "Route:", choices = c("IV" = "IV"))
        ),
        
        conditionalPanel(
          condition = "input.model_select == 'Adalimumab' | input.model_select == 'Etanercept' | input.model_select == 'Ustekinumab'",
          selectInput(paste0("cmt_", i), "Route:", choices = c("IV" = "IV", "SC" = "SC"))
        ),
        
        numericInput(paste0("wait_", i), "Wait (days):", value = 0, min = 0),
        br()  # Adds space between events
      )
    })
    do.call(tagList, event_ui)
  })
  
  
  # Observe the simulation button to handle custom regimen
  observeEvent(input$simulate, {
    # model_file <- paste0(input$model_select, ".cpp")
    # pbpk <- tryCatch({
    #   mread(model_file)
    # }, error = function(e) {
    #   showNotification("Model file loading failed. Check the model file path and syntax.", type = "error")
    #   NULL
    # })
    
    
    # Ensure pbpk is valid before proceeding
    # if (is.null(pbpk)) return()
    
    
    # This value will give calculate the end of simulation time
    end_value <- abs((input$GAinitial*7)) + (input$Delivery*7) 
    
    # Molecular weights for each of the antibodies
    mw_value <- case_when(input$model_select == "Infliximab"  ~ 149000, 
                          input$model_select == "Adalimumab"  ~ 148000,
                          input$model_select == "Etanercept"  ~ 150000,
                          input$model_select == "Ustekinumab" ~ 148600,
                          input$model_select == "Vedolizumab" ~ 146800
    )
    
    if (input$regimen_type == "Custom") {
      events <- list()
      for (i in 1:input$num_events) {
        ID <- 1
        amt <- input[[paste0("amt_", i)]]
        ii <- input[[paste0("ii_", i)]]
        addl <- input[[paste0("addl_", i)]]
        cmt <- if (input[[paste0("cmt_", i)]] == "IV") 2 else 1
        disease <- if(input$disease == "Ulcerative colitis") 0 else 1
        ev_i <- ev(amt = (amt * 1e6) / mw_value, ii = ii, addl = addl, cmt = cmt)
        events <- c(events, list(ev_i))
        if (i < input$num_events) {
          wait <- input[[paste0("wait_", i)]]
          events <- c(events, list(ev(amt=0, time = wait)))
        }
      }
      data_input <- do.call(seq, events) %>%
        as.data.frame() %>%
        mutate(GAinitial = input$GAinitial,
               Delivery = (end_value + input$GAinitial * 7) / 7,
               end = end_value,
               delta = input$delta,
               pregnancy = end_value + (input$GAinitial * 7)) %>% 
        as_data_set()
    } else {
      
      # Determine compartment based on administration route
      cmt_value <- if (input$admin_route == "IV") 2 else 1
      
      # Disease status for ustekinumab model
      disease_value <- if (input$disease == "Ulcerative colitis") 0 else 1
      
      # Dataset construction based on the dosing inputs
      data_input <- data.frame(
        ID = 1,
        amt = (input$amt * 1e6) / mw_value,
        ii = input$ii,
        addl = input$addl,
        cmt = cmt_value,
        disease = disease_value,
        GAinitial = input$GAinitial,
        end = end_value,
        delta = input$delta,
        Delivery = (end_value + input$GAinitial * 7) / 7,
        pregnancy = end_value + (input$GAinitial * 7)) %>%
        as_data_set()
    }
    
    # Run the simulation by feeding the dataset into the simulation function
    set.seed(2345)
    isim <- seq(input$n_vp)
    sim_output <- lapply(isim, vpcsim, data = data_input, model = get(input$model_select), mw = mw_value) %>% bind_rows()
    simulation_output(sim_output)
    
    GAinitial_vlaue <- input$GAinitial
    Delivery_value <- input$Delivery
    Delta_value <- (input$delta)/7 #in weeks
    
    # Process and store m and f data for plotting
    if (nrow(sim_output) > 0) {
      m <- sim_output %>%
        filter(GA %in% seq(GAinitial_vlaue, Delivery_value, Delta_value)) %>%
        group_by(GA) %>%
        summarise(m = median(conc_m, na.rm = TRUE), mq5 = quantile(conc_m, 0.05, na.rm = TRUE), mq95 = quantile(conc_m, 0.95, na.rm = TRUE)) %>%
        ungroup()
      
      f <- sim_output %>%
        filter(GA %in% seq(GAinitial_vlaue, Delivery_value, Delta_value)) %>%
        group_by(GA) %>%
        summarise(f = median(conc_f, na.rm = TRUE), fq5 = quantile(conc_f, 0.05, na.rm = TRUE), fq95 = quantile(conc_f, 0.95, na.rm = TRUE)) %>%
        ungroup()
      
      mf <- m %>% left_join(f, by = "GA")
      max_value <- max(c(mf$m, mf$f, mf$mq95, mf$fq95), na.rm = TRUE)
      
      sim_output <- sim_output %>% left_join(mf, by = "GA")
      Delivery_levels <- sim_output %>% filter(GA==Delivery) %>% distinct(GA, .keep_all = TRUE)
      
      # Render the ggplot in the UI
      output$conc_plot <- renderPlot({
        mf %>%
          ggplot(aes(GA)) +
          geom_ribbon(aes(ymin = mq5, ymax = mq95, fill = factor("Maternal", levels = c("Maternal", "Fetal"))), alpha = 0.7, size = 1) +
          geom_ribbon(aes(ymin = fq5, ymax = fq95,  fill = factor("Fetal", levels = c("Maternal", "Fetal"))), alpha = 0.7, size = 1) +
          geom_line(aes(y = m, color = factor("Maternal", levels = c("Maternal", "Fetal"))), size=1) +
          geom_line(aes(y = f, color = factor("Fetal", levels = c("Maternal", "Fetal"))), size=1) +
          geom_hline(yintercept = 5, color = "steelblue4", linetype = "dashed", size = 1) +
          geom_hline(yintercept = 20, color = "plum4", linetype = "dashed", size = 1) +
          theme_bw() +
          theme(
            legend.position="bottom",
            legend.direction="horizontal",
            #axis.line=element_line(size=1.5, linetype="solid"),
            axis.ticks=element_line(colour="black"),
            axis.title=element_text(size=20, face="bold"),
            plot.title=element_text(size=20, face="bold", hjust=0.5),
            legend.text=element_text(size=16),
            legend.title=element_text(size=16, face="bold"),
            plot.subtitle=element_text(size=16, face="bold"),
            axis.text=element_text(size=16),
            axis.text.y=element_text(size=16),
            strip.text = element_text(size = 16),
            strip.background = element_rect(color = "black", size = 1.5, fill = "NA"),
            panel.border = element_rect(color = "black", size = 1.5),
            plot.caption = element_text(size=16, hjust = 0)
          ) +  
          labs(
            #title = "IFX 5 and 10 mg/Kg IV, given every 6(Q6W) or 8(Q8W) weeks",
            x = "Gestational age (weeks)",
            y = "Maternal and fetal drug conc (μg/mL)",
            color = "Simulated exposure (median)",
            fill = "Prediction Interval (q5-q95)",
            caption = paste0("Median maternal delivery levels: ", round(Delivery_levels$m, 2), " (μg/mL)", "\nMedian fetal delivery levels: ", round(Delivery_levels$f, 2), " (μg/mL)"),
          ) +
          scale_y_log10(limits = c(0.1, max_value * 1.1), breaks = scales::breaks_log(),
                        labels = label_number(accuracy = 0.01, big.mark = "", decimal.mark = "."),
                        sec.axis = sec_axis(~ .* 1, breaks = scales::breaks_log(),  # Extend y-axis to accommodate max value
                                            labels = label_number(accuracy = 0.01, big.mark = "", decimal.mark = "."))) +  # Use label_number for formatting
          annotation_logticks(sides = "lr", short = unit(0.2, "cm"), mid = unit(0.2, "cm"), long = unit(0.4, "cm")) +
          scale_color_manual(values = c("Maternal" = "steelblue4", "Fetal" = "plum4"), guide=guide_legend(order=1)) +
          scale_fill_manual(values = c("Maternal" = "steelblue", "Fetal" = "plum"), guide=guide_legend(order=2))
        
        
        
      })
    } else {
      showNotification("Simulation output is empty. Check input parameters.", type = "warning")
    }
  })
  
  
  # Download Button for Simulation Output
  output$download_button_ui <- renderUI({
    if (!is.null(simulation_output())) {  # Check if simulation output is available
      downloadButton("download_data", "Download Simulation Output")
    }
  })
  
  # Download Handler for Simulation Output
  output$download_data <- downloadHandler(
    filename = function() {
      paste("simulation_output_", Sys.Date(), ".csv", sep = "")
    },
    content = function(file) {
      write.csv(simulation_output(), file, row.names = FALSE)
    }
  )
  
  
}

# Run the Shiny app
shinyApp(ui = ui, server = server)


